spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: identity-management
          uri: lb://IDENTITY-MANAGEMENT
          predicates:
            - Path=/api/v1/users/**
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8765/eureka/

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9799/realms/identity/
          jwk-set-uri: http://localhost:9799/realms/identity/protocol/openid-connect/certs
server:
  port: 1717
