spring:
  application:
    name: identity-management
  datasource:
    url: jdbc:postgresql://localhost/Identity_Manager
    password: oluwakemisola098
    username: postgres


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  keycloak:
    admin:
      clientId: identity-app
      clientSecret: ipvU92N5WKdnsVThf0q9qI5tuH1IEGwX
    realm: identity
    serverUrl: http://localhost:9799
    tokenUrl: http://localhost:9799/realms/identity/protocol/openid-connect/token
server:
  port: 1999