spring:
  application:
    name: identity-management


eureka:
  client:
    service-url:
      defaultZone: http://localhost:2009/eureka/

app:
  keycloak:
    admin:
      clientId: identity-app
      clientSecret: ipvU92N5WKdnsVThf0q9qI5tuH1IEGwX
    realm: identity
    serverUrl: http://localhost:9799
    tokenUrl: http://localhost:9799/realms/identity/protocol/openid-connect/token
server:
  port: 6841