spring:
  application:
    name: identity-management

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2009/eureka/

app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: IaYscf7zVFVoPUB6iCvxl6ilMDLaUEW3
    realm: spring
    serverUrl: http://localhost:9082
    tokenUrl: http://localhost:9082/realms/spring/protocol/openid-connect/token