spring:
  application:
    name: identity-management


  pulsar:
    client:
          service-url: pulsar://localhost:6655
  datasource:
    username: postgres
    password: oluwakemisola098
    url: jdbc:postgresql://localhost:5432/Identity_Manager


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  keycloak:
    admin:
      clientId: identity-app
      clientSecret: ipvU92N5WKdnsVThf0q9qI5tuH1IEGwX
    realm: identity
    serverUrl: http://localhost:9799
    tokenUrl: http://localhost:9799/realms/identity/protocol/openid-connect/token
server:
  port: 1818
