eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: wallet-management

  datasource:
    url: jdbc:postgresql://localhost/Wallet
    username: postgres
    password: oluwakemisola098
  jpa:
    hibernate:
      ddl-auto: update

  pulsar:
    client:
      service-url: pulsar://localhost:6655

  monnify:
    api:
      key: MK_TEST_SUUMRYA4Y1
    secret:
      key: SY5DCDMCQNYUDAEJ9D8LEJ5360B3F8ML
    contract_code: 4605783897
    base_url: https://sandbox.monnify.com
    transaction:
      redirect_url: https://my-merchants-page.com/transaction/confirm
      initiate_url: /api/v1/merchant/transactions/init-transaction
      login_url: https://sandbox.monnify.com/api/v1/auth/login
      transfer_url: api/v1/merchant/bank-transfer/init-payment


server:
  port: 0000
